spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-rest-db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: "classpath:/liquibase/db-changelog-master.yaml"
