spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-rest-db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  messages:
    basename: messages/messages, messages/validation/messages
  web:
    locale: en
  liquibase:
    change-log: "classpath:/liquibase/db-changelog-master.yaml"

swagger:
  enabled: true
